# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - main
      - test/**
  workflow_dispatch:
    inputs:
      locale:
        type: choice
        required: true
        description: Locale
        options:
          - en-GB
          - pl-PL
        default: en-GB
  # Scheduled run is not required right now, but it can be easily uncommented in case of any need
  # schedule:
  #   # At 00:00 on every day-of-week from Monday through Friday
  #   - cron: '0 0 * * 1-5'

env:
  CI: true
  LOCALE: ${{ github.event.inputs.locale }}

jobs:
  build:
    name: 'Build ${{ github.event.inputs.locale }}'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - name: 'Run tests ${{ github.event.inputs.locale }}'
        run: npm test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 30
